# Generated by Django 4.2.24 on 2025-11-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='fecha_venc',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
