# Generated by Django 4.2.24 on 2025-11-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_lote_fecha_venc'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='requiere_receta',
            field=models.BooleanField(default=False),
        ),
    ]
