# Generated by Django 4.2.24 on 2025-11-08 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_producto_requiere_receta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='requiere_receta',
        ),
    ]
