# Generated by Django 4.2.24 on 2025-11-11 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_producto_requiere_receta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='RandomForestRegressor', max_length=100)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('r2_score', models.FloatField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('training_samples', models.IntegerField(default=0)),
                ('features_used', models.JSONField(default=list)),
                ('model_path', models.CharField(max_length=500)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'model_metrics',
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField()),
                ('predicted_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('predicted_quantity', models.IntegerField(blank=True, null=True)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_quantity', models.IntegerField(blank=True, null=True)),
                ('confidence_interval_lower', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('confidence_interval_upper', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='api.categoria')),
                ('model_metrics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='api.modelmetrics')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='api.producto')),
            ],
            options={
                'db_table': 'sales_prediction',
                'ordering': ['prediction_date'],
            },
        ),
        migrations.AddIndex(
            model_name='modelmetrics',
            index=models.Index(fields=['is_active', '-trained_at'], name='model_metri_is_acti_883e57_idx'),
        ),
        migrations.AddIndex(
            model_name='salesprediction',
            index=models.Index(fields=['prediction_date', 'categoria'], name='sales_predi_predict_59ead5_idx'),
        ),
        migrations.AddIndex(
            model_name='salesprediction',
            index=models.Index(fields=['prediction_date', 'producto'], name='sales_predi_predict_bf4003_idx'),
        ),
        migrations.AddIndex(
            model_name='salesprediction',
            index=models.Index(fields=['model_metrics', 'prediction_date'], name='sales_predi_model_m_22a2eb_idx'),
        ),
    ]
